---
language: "node_js"
node_js: "stable"
sudo: false
addons:
  apt:
    sources:
      - "ubuntu-toolchain-r-test"
    packages:
      - "g++-4.8"
cache:
  apt: true
  directories:
    - "node_modules"
env:
  global:
    - "CXX=g++-4.8"
